### ISSUE TITLE
pip package installation failed

### ISSUE THREAD

**Issue by julianmorenomotta** [ynop/audiomate#143]
used `pip install audiomate`

And yielded this answer
```
Collecting audiomate
  Using cached audiomate-6.0.0-py3-none-any.whl.metadata (7.7 kB)
Collecting audioread==2.1.8 (from audiomate)
  Using cached audioread-2.1.8.tar.gz (21 kB)
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error
  
  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [6 lines of output]
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/private/var/folders/_6/cj2y6ttx48b7332gvfxjrfjw0000gn/T/pip-install-fn_lys3z/audioread_3996d43fe0b542edb22256cc8daefedf/setup.py", line 17, in <module>
          import imp
      ModuleNotFoundError: No module named 'imp'
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.

```

**Comment by joyeusenoelle** [comment]
`imp` was removed from the default libraries in Python 3.12 in favor of `importlib`. Since audiomate hasn't been updated in almost four years, I'm not sure what the odds of this being corrected are, but in the meantime a potential workaround is to use `pyenv` to install Python 3.11, which still supports `imp`.

**Edit**: On looking into this further, `imp` is used in the version of `audioread` that audiomate requires. It's no longer used in the most recent version (3.0.1), and the functionality audiomate adds to it (only loading the backends once) is now built into audioread, so updating should be pretty straightforward.
